# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CuFW8KCpyCSgzSys4RiKwpjfTdomX2Vt
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile predict.py

import numpy as np
import cv2
import tensorflow as tf
import os
import matplotlib.pyplot as plt # 新增：用于显示图片

# 1. 明确定义损失函数
def dice_loss(y_true, y_pred):
    y_true_f = tf.reshape(tf.cast(y_true, tf.float32), [-1])
    y_pred_f = tf.reshape(tf.cast(y_pred, tf.float32), [-1])
    intersection = tf.reduce_sum(y_true_f * y_pred_f)
    return 1.0 - (2.0 * intersection + 1.0) / (tf.reduce_sum(y_true_f) + tf.reduce_sum(y_pred_f) + 1.0)

class BreastUltrasoundPredictor:
    def __init__(self, model_path):
        os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
        custom_dict = {'dice_loss': dice_loss}
        print("Loading optimized Attention U-Net model...")
        self.model = tf.keras.models.load_model(model_path, custom_objects=custom_dict, compile=False)
        self.input_size = (128, 128)

    def preprocess(self, img_path):
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if img is None: raise FileNotFoundError(f"Image not found: {img_path}")
        # 保存原图用于最后对比显示
        original_img = cv2.resize(img, self.input_size)
        img_array = original_img.astype('float32') / 255.0
        return np.expand_dims(img_array, axis=(0, -1)), original_img

    def predict(self, img_path):
        processed_img, original_img = self.preprocess(img_path)
        prediction = self.model.predict(processed_img, verbose=0)
        mask = (prediction[0, :, :, 0] > 0.5).astype(np.uint8)
        return original_img, mask

# 执行入口
if __name__ == "__main__":
    MODEL_FILE = 'unet_breast_31m_dice078.h5'
    REAL_IMAGE = '/content/malignant (1).png'

    try:
        predictor = BreastUltrasoundPredictor(MODEL_FILE)
        print("Model loaded successfully!")

        # 执行推理
        original, pred_mask = predictor.predict(REAL_IMAGE)
        print("Inference successful. Displaying results...")

        # 绘图对比显示
        plt.figure(figsize=(10, 5))

        plt.subplot(1, 2, 1)
        plt.imshow(original, cmap='gray')
        plt.title("Original Ultrasound")
        plt.axis('off')

        plt.subplot(1, 2, 2)
        plt.imshow(pred_mask, cmap='jet', alpha=0.5) # 使用彩色显示病灶区域
        plt.title("Predicted Lesion Area")
        plt.axis('off')

        plt.show()

    except Exception as e:
        print(f"An error occurred: {e}")

!python predict.py
